import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const runtimeRoot = resolve(repoRoot, "src", "runtime");
const headersDir = join(runtimeRoot, "headers");
const sourcesDir = join(runtimeRoot, "sources");
const vendorDir = join(runtimeRoot, "vendor");
const outputPath = join(runtimeRoot, "embedded.ts");

function readDirectory(directory) {
  const entries = readdirSync(directory).filter((name) => /\.(cpp|hpp)$/u.test(name));
  const map = {};
  for (const name of entries) {
    const key = name.replace(/\.(cpp|hpp)$/u, "");
    const content = readFileSync(join(directory, name), "utf8");
    map[key] = content.replace(/\r\n/gu, "\n").replace(/\n+$/u, "");
  }
  return map;
}

function readVendor(name) {
  const filepath = join(vendorDir, `${name}.hpp`);
  if (!existsSync(filepath)) {
    throw new Error(`Vendor header ${filepath} not found.`);
  }
  return readFileSync(filepath, "utf8").replace(/\r\n/gu, "\n").replace(/\n+$/u, "");
}

const headers = readDirectory(headersDir);
const sources = readDirectory(sourcesDir);

if (sources.http !== undefined) {
  const vendor = readVendor("cpp-httplib");
  const pragmaPush = [
    "#pragma GCC diagnostic push",
    "#pragma GCC diagnostic ignored \"-Wall\"",
    "#pragma GCC diagnostic ignored \"-Wextra\"",
    "#pragma GCC diagnostic ignored \"-Wpedantic\"",
    "#pragma GCC diagnostic ignored \"-Wunused-parameter\"",
    "#pragma GCC diagnostic ignored \"-Wunused-function\"",
    "#pragma GCC diagnostic ignored \"-Wunused-variable\"",
    "#pragma GCC diagnostic ignored \"-Wunused-but-set-variable\"",
    "#pragma GCC diagnostic ignored \"-Wsign-compare\"",
    "#pragma GCC diagnostic ignored \"-Wmissing-field-initializers\"",
    "#pragma GCC diagnostic ignored \"-Wdeprecated-declarations\"",
    "#pragma GCC diagnostic ignored \"-Wtype-limits\"",
    "#pragma GCC diagnostic ignored \"-Wparentheses\"",
    "#pragma GCC diagnostic ignored \"-Wnarrowing\""
  ].join("\n");
  const pragmaPop = "#pragma GCC diagnostic pop";
  sources.http = `${pragmaPush}\n${vendor}\n${pragmaPop}\n\n${sources.http}`;
}

function emitRecord(name, map) {
  const entries = Object.keys(map)
    .sort()
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(map[key])}`)
    .join(",\n");
  return `export const ${name}: Record<string, string> = {\n${entries}\n};`;
}

const banner = "// AUTO-GENERATED by scripts/embed-runtime.mjs — DO NOT EDIT BY HAND.\n";
const body = [emitRecord("RUNTIME_HEADERS", headers), emitRecord("RUNTIME_SOURCES", sources)].join("\n\n");

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${banner}\n${body}\n`, "utf8");

const totalBytes = Object.values(headers).concat(Object.values(sources)).reduce((sum, value) => sum + value.length, 0);
console.log(
  `Embedded ${Object.keys(headers).length} header(s) and ${Object.keys(sources).length} source(s) (${totalBytes} bytes) into ${outputPath}.`
);
